### PR TITLE
support system preferredmodule

### PR DESCRIPTION
**Pull request by seblemaguer**
Add default preferred modules without any voice dependency

### CODE REVIEW

**Comment by psibre** [comment]
@seblemaguer do we have some way of testing this new feature?

**Comment by seblemaguer** [comment]
I'm working on it :)

**Comment by seblemaguer** [comment]
I think this time that's ok. I will merge that tomorrow except if you have a comment (I still have formatting problems just due to trailing spaces....

**Comment by psibre** [comment]
@seblemaguer Could you refactor the code a bit and rename the property? Following the [conventions in `marybase.config`](../blob/be2f8ca2d25d43dfee55977ffd8e3fc7da23a3a4/marytts-runtime/conf/marybase.config#L58-L99), perhaps something like `prefer.modules.classes.list`; you can also draw on some of the helper methods such as MaryProperties.getList...

**Comment by seblemaguer** [comment]
actually I followed the convention in "voice" (see line 211 in Voice.java) for the name but nopb. We just have to homogenize that properly. Concerning the getList, I don't get it ? There is no such things and I don't see why introducing it. Can you explain maybe a little bit more ? thanks

**Comment by psibre** [comment]
@seblemaguer the `*.list` properties are special in that they are parsed into an ArrayList by [MaryProperties.getList](../blob/d7b57e81d0e8e9abbd4f8be4ca66766ff700687c/marytts-runtime/src/main/java/marytts/server/MaryProperties.java#L56-L69). This lets us provide preferred modules in various config files, and avoids the need for an ad-hoc StringTokenizer inside ModuleRegistry.

**Comment by psibre** [comment]
@seblemaguer haha, comment race!

**Pull request merged**
