### PR TITLE
updated and corrected phonetic transcriptions

### PR DESCRIPTION
**Pull request by PeterGilles**

### CODE REVIEW

**Comment by seblemaguer** [comment]
thanks a lot

**Comment by PeterGilles** [comment]
Please tell me, how many phonetic transcriptions you ideally need. I could provide a lot more.

**Comment by psibre** [comment]
@PeterGilles I noticed that the updated lexicon seems to be missing part of speech tags. Is this deliberate? We don't need them for syntactic processing directly, but in the lexicon they might help with homograph disambiguation.

**Comment by PeterGilles** [comment]
I actually don't have the POS information for all words in this expanded list. If they are really needed, I'll try to find a way to include them.

**Comment by psibre** [comment]
I don't think it's critical... we can retrain the legacy LTS resources without them.

**Pull request merged**
