### PR TITLE
Remove redstart and transcription

### PR DESCRIPTION
**Pull request by seblemaguer**

### CODE REVIEW

**Comment by psibre** [comment]
Just to keep our PRs semantically transparent, can we split this into one PR that drops unmaintained legacy modules, and another that updates OpenNLP?

**Comment by psibre** [comment]
@seblemaguer Could you please strip 19a748d0e0b1ead9239b49917376800e93842049 from the tip of your branch?

**Comment by seblemaguer** [comment]
fair enough.

**Comment by psibre** [comment]
Please also remove references to the deleted Gradle projects from `settings.gradle` and `marytts-assembly/assembly-builder/build.gradle`, and remove `marytts-assembly/assembly-builder/src/builder/bin/redstart.*`

**Comment by psibre** [comment]
Ah, never mind, you were too fast! =)

We can remove those things during other cleanup PRs.

**Comment by seblemaguer** [comment]
oupsy :D

**Pull request merged**
