### PR TITLE
Issue#428

### PR DESCRIPTION
**Pull request by Rootex**
The Unit test for phonemizing greek words.

### CODE REVIEW

**Comment by seblemaguer** [comment]
Hello,

you have a null pointer exception in your build :)

**Comment by Rootex** [comment]
ok i will get to it. :D

**Comment by psibre** [comment]
@Rootex pls clean up a bit

**Comment by psibre** [comment]
@Rootex @seblemaguer For the record, it would be nice to clean up PRs like this so that they contain only well-formed, relevant commits. If there's any "cleanup" to do, commits can, and should be, replaced before merging...

**Comment by Rootex** [comment]
OK Noted for next time.

**Pull request merged**
