### PR TITLE
Test windows and macos via travis

### PR DESCRIPTION
**Pull request by seblemaguer**

### CODE REVIEW

**Comment by seblemaguer** [comment]
1.9 and 1.10 are facing a certificate issue when downloading gradle packages. It is disabled for now and need more investigation

**Comment by seblemaguer** [comment]
@psibre don't worry about commit 5d3d0e3 I plan to rebase the branch when I will have a clean solution for the previous issue

**Comment by psibre** [comment]
I wonder if it's worth throwing all of the Travis stuff out the window just to support Windows on Travis... Maybe we want to use AppVeyor instead?

**Comment by psibre** [comment]
Could we add another env or something so that the checks in the "Checks" tab for the PRs are more descriptive?

**Comment by seblemaguer** [comment]
Yup ok I will have a look

**Pull request merged**
