### PR TITLE
newly created package-info.java files under their respective directories

### PR DESCRIPTION
**Pull request by aitorme**
These files are the substitute for the already existing package.html files, which are located under resources, and now they belong in java directory.

### CODE REVIEW

**Comment by psibre** [comment]
What about these packages?
```
marytts.util.data.audio
marytts.util.data.text
marytts.util.math
marytts.util.signal
Jampack
marytts.signalproc.effects
```

**Comment by psibre** [comment]
@aitorme can you merge from [the branch in my fork](/psibre/marytts/tree/packageinfo)?

**Comment by psibre** [comment]
Actually I just noticed that the line wrapping in a few `package-info.java` files is off.
Also, the ones for
```
marytts.signalproc.sinusoidal
marytts.signalproc.sinusoidal.hntm.synthesis
marytts.signalproc
marytts.signalproc.analysis
marytts.signalproc.adaptation.prosody
```
contain various broken itemize lists; they should be fixed with `<ul><li/>...</ul>`.

**Comment by aitorme** [comment]
the last commit fixes the broken itemize lists, but which files have the line wrapping off?

**Comment by psibre** [comment]
@aitorme thanks, you can delete your `packageinfo` branch.

**Pull request closed without merging**
