### PR TITLE
Fix some cases where Data is too long

### PR DESCRIPTION
**Pull request by yuripourre**
Related to #823

### CODE REVIEW

**Comment by psibre** [comment]
Thanks for your contribution! Since I personally have never used this feature, could you please explain what the error was, and how your commit fixes it?

**Comment by yuripourre** [comment]
Sure, let me explain briefly but I can give more information later if needed.

I was following the tutorial to create a new voice but during database split script the data (from the xml) that comes from rev_revision (I have to confirm the exact name) was bigger than 255 bytes (tinyblob).
Then the java code throws an exception saying that data is too long.

Changing the column type from tinyblob to blob increases the size of the column and solved the problem in my case.

**Comment by psibre** [comment]
Thanks for the details! Could you please point out which field needed more than 255 bytes? Is it the phoneme?

**Comment by yuripourre** [comment]
> Thanks for the details! Could you please point out which field needed more than 255 bytes? Is it the phoneme?

No, it is during wikipedia xml dumping. The exception is thrown when revision's comment is greater then tinyblob size.

**Comment by psibre** [comment]
Oh I see! That's a bug -- thanks for the fix!

**Pull request merged**
