### PR TITLE
guava: 24.1.1-jre

### PR DESCRIPTION
**Pull request by dargmuesli**
Should fix https://app.snyk.io/vuln/SNYK-JAVA-COMGOOGLEGUAVA-32236.

### CODE REVIEW

**Comment by psibre** [comment]
@dargmuesli Thanks for your contribution! I can cherry-pick your commits in a new PR, or you can rebase on marytts/master.

**Comment by dargmuesli** [comment]
Rebased :)

**Comment by dargmuesli** [comment]
Is there going to be a new 5.x release, containing these vulnerability fixes?

**Comment by seblemaguer** [comment]
@dargmuesli yes that is the plan :) we do our best for in all cases :D

**Comment by dargmuesli** [comment]
Great! Thank you :*

**Comment by dargmuesli** [comment]
Sorry to bother, but when can the patch release be expected?

**Comment by seblemaguer** [comment]
I prefer to not give a date yet but as we have a set of pull request we have to merge (namely from #962 to #977) and then we will release the patch. But some pull requests require modifications in other repositories and this is currently in process. Therefore, the only thing I can say is it should be soon

**Comment by psibre** [comment]
If it helps, we could publish a snapshot to oss.jfrog.io...

**Comment by dargmuesli** [comment]
I think soon is enough for me, nothing critical here :)
Thank you for the answers!

**Pull request merged**
