### PR TITLE
Fix  for #280 #467 #468 #469 #464

### PR DESCRIPTION
**Pull request by attacomsian**

### CODE REVIEW

**Comment by seblemaguer** [comment]
Seems to be fine for me. Can you run again the travis part and stay on this page to be sure that it actually processing ?

**Comment by attacomsian** [comment]
I tried but the result was same. It was processing but got failed at the end. Following is the warning I found in log:
`[WARNING] Cannot get the branch information from the git repository: 
Detecting the current branch failed: fatal: ref HEAD is not a symbolic ref`

**Comment by psibre** [comment]
@attacomsian OK, our CI on Travis works again. Your error is due to the shallow clone depth there, but even rebasing would not solve the issue.
Of course it works within Eclipse, but once MaryTTS is run from an installation (i.e., using the `bin/marytts` script under the build directory), the hard-coded source path to the DTDs are no longer valid, and we get essentially the same error.

**Comment by psibre** [comment]
Also, this PR is a bit messy. I would prefer to close it in favor of two separate PRs for #469 and #468, respectively.

**Pull request closed without merging**
