### PR TITLE
Fix warnings

### PR DESCRIPTION
**Pull request by seblemaguer**

### CODE REVIEW

**Comment by seblemaguer** [comment]
@psibre What do we do with the builder? Is it still needed?

**Comment by psibre** [comment]
Thanks for the hard work!

I'm afraid marytts-builder is still a dependency of the voicebuilding plugin. (I'm nearly done upgradling that, but it's tricky due to its dependency on the Praat wrapper plugin...)

**Comment by seblemaguer** [comment]
ok, if you have a sample of the voice building, could you run it using this branch? Just to be sure :D

Thanks,
Seb

**Comment by psibre** [comment]
For the voicebuilding plugin, we need marytts-builder published.

**Pull request merged**
