### PR TITLE
Component installer License download re-code following  #395

### PR DESCRIPTION
**Pull request by Rootex**
Some changes where made to the LicenseRegistry file, basically re coding the method used for downloading licenses, to use the Apache Commons method. And i stuck with the try-with-resources convention since it enforces exception handling more than the conventional try-catch in java 6 and lower. Note: try-with-resources was introduced in JAVA 7 "If that wont be an issue?"

### CODE REVIEW

**Comment by psibre** [comment]
@Rootex can you strip 08a0498 from this PR (`git reset` locally, then `git push -f`)?

**Comment by psibre** [comment]
Incidentally, could you also please import the `eclipse-code-style.xml` into your Eclipse and auto-format `LicenseRegistry.java`?

**Comment by psibre** [comment]
> Note: try-with-resources was introduced in JAVA 7 "If that wont be an issue?"

Indeed, this is great -- we require Java 7 but haven't actually introduced any of the syntactic sugar or other features it provides. =)

**Comment by psibre** [comment]
:+1: for using `IOUtils`

**Comment by Rootex** [comment]
Thank you :)

**Pull request merged**
